version: "3"

services:
    Postgres:
        image: "postgres"
        container_name: "Postgres"
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
        command: -p ${POSTGRES_PORT}
        networks:
            - network

    pgAdmin:
        image: "dpage/pgadmin4"
        container_name: "pgAdmin"
        depends_on:
            - "Postgres"
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - "./config/pgadmin/servers.json:/pgadmin4/servers.json" # JSON file telling pgAdmin what servers to connect to
        networks:
            - network

    RabbitMQ:
        image: rabbitmq:3-management
        container_name: "RabbitMQ"
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
        ports:
            - "${RABBITMQ_PORT}:5672"
            - "${RABBITMQ_MANAGEMENT_PORT}:15672"
        networks:
            - network

    mod-update-scheduler:
        container_name: "ModUpdateScheduler"
        build:
            context: ./Src/
            dockerfile: ./ModUpdateScheduler/Dockerfile
        #network_mode: "host"
        depends_on:
            - "Postgres"
            - "RabbitMQ"
        environment:
            - POSTGRES_CONNECTION_STRING=Server=Postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
            - RABBITMQ_PORT
            - ADMINISTRATOR_USERNAME
            - ADMINISTRATOR_EMAIL
            - ADMINISTRATOR_PASSWORD
            - ADMINISTRATOR_ID
            - MODUPDATESCHEDULER_USERNAME
            - MODUPDATESCHEDULER_EMAIL
            - MODUPDATESCHEDULER_PASSWORD
            - MODUPDATESCHEDULER_ID
            - MODUPDATEWORKER_USERNAME
            - MODUPDATEWORKER_EMAIL
            - MODUPDATEWORKER_PASSWORD
            - MODUPDATEWORKER_ID

        networks:
            - network

volumes:
    postgres-data:
    rabbit-mq-data:

networks:
    network: {}