version: "3"

services:
    postgres:
        container_name: "postgres"
        image: "postgres"
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
        command: -p ${POSTGRES_PORT}

    pgadmin:
        container_name: "pgadmin"
        image: "dpage/pgadmin4"
        depends_on:
            - "postgres"
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - "./config/pgadmin/servers.json:/pgadmin4/servers.json" # JSON file telling pgAdmin what servers to connect to
            
    fluent-migrator:
        container_name: "fluent-migrator"
        build: ./PostgresMigrator
        network_mode: "host"
        depends_on:
            - "postgres"
        environment:
            - POSTGRES_PORT
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_CONNECTION_STRING=Server=localhost;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
        restart: "on-failure:3"

volumes:
    postgres-data: