name: Code Coverage

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    code-coverage:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/download-artifact@master
              with:
                #name: code-coverage-reports
                path: ./Tests/TestResults/

            - name: Upload Coverage Reports to Codecov
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: ./Tests/TestResults/Domain.UnitTests.xml,./Tests/TestResults/Application.UnitTests.xml,./Tests/TestResults/Infrastructure.UnitTests.xml,./Tests/TestResults/ModUpdateScheduler.UnitTests.xml
                flags: UnitTests
                fail_ci_if_error: true
