name: .NET Core Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: windows something???

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Domain Unit Tests
      #run: dotnet test --no-restore --verbosity normal
      run: dotnet test ./Tests/Domain.UnitTests/Domain.UnitTests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=\"json,lcov,opencover\" /p:CoverletOutput=\"../TestResults/\" /maxcpucount:1

    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestResults/coverage.info,./TestResults/coverage.json,./TestResults/coverage.opencover.xml
        flags: UnitTests
        fail_ci_if_error: true
