name: Tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 3.1.301

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Domain Unit Tests
              run: dotnet test --no-restore ./Tests/Domain.UnitTests/Domain.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"../TestResults/Domain.UnitTests.xml\" /p:Include=\"[FactorioProductionCells.Domain*]*\" /maxcpucount:1

            - name: Application Unit Tests
              run: dotnet test --no-restore ./Tests/Application.UnitTests/Application.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"../TestResults/Application.UnitTests.xml\" /p:Include=\"[FactorioProductionCells.Application*]*\" /maxcpucount:1

            - name: Infrastructure Unit Tests
              run: dotnet test --no-restore ./Tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"../TestResults/Infrastructure.UnitTests.xml\" /p:Include=\"[FactorioProductionCells.Infrastructure*]*\" /p:ExcludeByFile=\"**/Migrations/*.cs\" /maxcpucount:1

            - name: ModUpdateScheduler Unit Tests
              run: dotnet test --no-restore ./Tests/ModUpdateScheduler.UnitTests/ModUpdateScheduler.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"../TestResults/ModUpdateScheduler.UnitTests.xml\"  /p:Include=\"[ModUpdateScheduler*]*\" /maxcpucount:1

            - name: Upload
            - uses: actions/upload-artifact@master
              with:
                name: code-coverage-reports
                path: ./Tests/TestResults/
